---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
library(seasonal)
library(zoo)
industrial_prod <- window(seasonal::iip, start = 2000)
industrial_prod
```
```{r}
iip_data <- data.frame(Y=as.matrix(seasonal::iip), date=as.Date(zoo::as.yearmon(time(seasonal::iip))))
iip_data
```
```{r}
get_vedic_date<- function(julian_day, place) {
  
masa_num <- VedicDateTime::masa(julian_day, place)
vikram_samvatsara = VedicDateTime::elapsed_year(julian_day, masa_num)[5]
tithi_ = tithi(julian_day, place)[1]
masa_ = masa(julian_day, place)[1]
vedic_dates = paste(as.character(vikram_samvatsara),"-",as.character(masa_),"-",as.character(tithi_), sep = "") 
return(vedic_dates)
}
```

```{r}
date<- iip_data$date
date <- as.POSIXct.Date(date)
julianday_iip <- insol::JD(date)
julianday_iip
```


```{r}
place <- c(15.34, 75.13, +5.5) #Latitude, Longitude and timezone of the location
iip_vedic_calendar = c()
for (i in 1:length(julianday_iip)) 
{
iip_vedic_calendar = c(iip_vedic_calendar, get_vedic_date(julianday_iip[i], place))
}
iip_vedic_calendar
```

```{r}
iip_data$date <- iip_vedic_calendar
iip_data
```
```{r}
iip_vedic_date_ts <- ts(iip_data$Y,start=c(2061,2))
```


